stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
      - src/data/data_ingestion.py
      - data/external/Chrun.csv
    outs:
      - data/raw/train.csv
      - data/raw/validation.csv
      - data/raw/test.csv