stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
      - src/data/data_ingestion.py
      - data/external/Chrun.csv
    outs:
      - data/raw/train.csv
      - data/raw/validation.csv
      - data/raw/test.csv
  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
      - src/data/data_preprocessing.py
      - data/raw/train.csv
      - data/raw/test.csv
    outs:
      - data/interim/train_cleaned.csv
      - data/interim/validation_cleaned.csv
      - data/interim/test_cleaned.csv
  feature_engineering:
    cmd: python src/features/run_feature_engineering.py
    deps:
      - src/features/run_feature_engineering.py
      - src/features/feature_engineering.py
      - data/interim/train_cleaned.csv
      - data/interim/validation_cleaned.csv
      - data/interim/test_cleaned.csv
    outs:
      - data/processed/train_features.csv
      - data/processed/validation_features.csv
      - data/processed/test_features.csv
      - models/automl_brain/feature_transformer.pkl