
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: inference-canary-ingress
  namespace: automl-brain
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "10"  
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: inference-canary-service  
            port:
              number: 80