
apiVersion: v1
kind: Service
metadata:
  name: inference-canary-service
  namespace: automl-brain
  labels:
    app: churn-inference
    track: canary
spec:
  type: ClusterIP
  selector:
    app: churn-inference
    track: canary
  ports:
  - port: 80
    targetPort: 8000